- README.md
- assembly/etc/che-plugin.yaml
- build.sh
> Fix outdated README.md and fix CHE plugin scripts.

- .travis.yml
https://github.com/eclipse/che-machine-exec/issues/18
> Remove deploy section from travis file. We don't use it.

- api/model/model_types.go
- exec/kubernetes-infra/kubernetes_exec_manager.go
https://github.com/eclipse/che/issues/11866
> Add workaround to handle current working directory for exec.

- exec/kubernetes-infra/kubernetes_exec_manager.go
Referenced issue:
https://github.com/eclipse/che-theia/issues/138
> Fix command without cwd.

- devfile.yaml
> Fix devfile.

- devfile.yaml
Updates devfile to newer specification
> Update the che-machine-exec repo devfile to new schema

- exec/kubernetes-infra/command_resolver.go
- exec/kubernetes-infra/comnand_resolver_test.go
https://github.com/eclipse/che/issues/13977
> Use sh instead of nologin shell.

- dockerfiles/ci/Dockerfile
- rhel.Dockerfile
> Optimize dockerfiles to dicreasy amount image layers.

- Dockerfile
https://github.com/eclipse/che/issues/15602
> Remove too early applied changes.

- rhel.Dockerfile
Change-Id:...
update to latest base image
Change-Id: I73fc89449ec06c8ee25817d8dc2618d10a2a82c2
> update to latest base image

- Dockerfile
Initially, it was supposed that there is not shell available in che-machine container.
But then by mistake, then was added the wrong usage of ARG because its value is not propagated during different stages of the multistage build. As result, everything from cloud-shell-builder was added into the scratch target image.
Also, initialization of user was fixed in the following way https://stackoverflow.com/questions/49955097/how-do-i-add-a-user-when-im-using-alpine-as-a-base-image/55757473#55757473
It's tested and the image is available by `sleshchenko/che-machine-exec:new-dockerfile`
:warning: rhel based docker image is not updated since Cloud Shell is not expected in CRW for now. Let me know if you have some concerts related to it.
P.S. Thank @AndrienkoAleksandr for helping me a lot in …
> Do not provision everything from node:10.16-alpine into scratch

- devfile.yaml
> Fix che-theia image reference in the devfile.

- devfile.yaml
> Set up RAM for devfile components. Add debug configuration.

- exec/kubernetes_exec_manager.go
> Initialize map to avoid NPE

- cloud-shell/src/index.ts
https://github.com/eclipse/che/issues/16249
> Display permission error.

- exec/kubernetes_exec_manager.go
- main.go
It implements the second option described in https://github.com/eclipse/che/issues/16638
> Improved errors when token is missing or filtered containers list is empty

- api/rest/activity.go
- api/rest/execKubeConfig.go
- exec/kubernetes_exec_manager.go
- main.go
This PR adds a REST API method to allow register activity.
This method is just PUT without a body that is supposed to response 204/403
> Add a REST API method to allow register activity

- activity/manager.go
Fix devworkspace api group to fix idling
https://issues.redhat.com/browse/WTO-39 
1. Update devworkspace controller to use image from that PR, like
```
- name: RELATED_IMAGE_plugin_redhat_developer_web_terminal_4_5_0
-              value: "quay.io/wto/web-terminal-exec:1.0"
+              value: "sleshchenko/che-machine-exec:devworkspace-fix"
```
2. Deploy devworkspace controller.
3. Start terminal
4. Test that devworkspace is stopped after 15 minutes of inactivity.
> Fix devworkspace api group to fix idling

- .github/CODEOWNERS
Remove myself (vparfonov) from CODEOWNER
> Remove myself (vparfonov) from CODEOWNER

- README.md
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
> Fix readme coverage link gap

- .github/workflows/release.yaml
- make-release.sh
Add various fixes to release workflow
> Fix release workflow

- cfg/cfg.go
Adapt Che Machine Exec to devworkspace workspace engine
it's draft since I haven't tested it yet
> Adapt Che Machine Exec to devworkspace workspace engine

- .github/workflows/release.yaml
notify mattermost when che machine exec release is done, with link to quay artifacts
Change-Id: Iafd0515f147b3ff6dea33a9af1dd2169c31bfe42
N/A
https://github.com/eclipse/che/issues/18906
N/A
> https://github.com/eclipse/che/issues/18906 notify mattermost when release done

- .github/workflows/release.yaml
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
> Remove required parameter from the release

- .github/workflows/release.yaml
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
> Fix release workflow script when no-commit is empty

- cfg/cfg.go
Adapt to DWO change where new label is devworkspace_id
:warning: it must be merged in sync with https://github.com/devfile/devworkspace-operator/pull/322
> Adapt to DWO change where new label is devworkspace_id

- README.md
- make-release.sh
https://github.com/eclipse/che/issues/18509
Add `linux/arm64` release image build
> Add `linux/arm64` release image build

- .github/workflows/gh_actions_push.yaml
- CONTRIBUTING.md
- README.md
- make-release.sh
> Replace references from master to main

- .github/dependabot.yml
Enable Dependabot to get updates for Dockefiles
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
> Enable Dependabot for Dockerfiles

- build/dockerfiles/rhel.Dockerfile
https://github.com/eclipse/che/issues/19593 try using registry.access.redhat.com/ubi8/go-toolset instead of registry.redhat.io/ubi8/go-toolset to make dependabot happier
Change-Id: I0e9d86896306b6eb4c7504c3bd89d5d95e416f1a
N/A
N/A (or see commit message above for issue number)
N/A
> 19593 Use registry.access.redhat.com/ubi8/go-toolset public registry instead of registry.redhat.io/ubi8/go-toolset that requires auth

- .github/workflows/license.yaml
- build/dockerfiles/Dockerfile
- devfile.yaml
* use golang 1.15 in Dockerfile
* use the latest che-golang in devfile
> fix: golang in Dockerfile

- build/dockerfiles/rhel.Dockerfile
19762 - can't use ubi8-minimal:8.4 and then install golang as Brew builds fail with
error: No available modular metadata for modular package 'golang-1.15.7-1.module+el8.4.0+9580+3b0e6c24.ppc64le'; cannot be installed on the system
Change-Id: I506f95063e33f2233edda790bd0f69a4d061a088
N/A
N/A (or see commit message above for issue number)
N/A
> chore: eclipse/che#19762 - can't use ubi8-minimal:8.4 and then install golang as Brew builds fail

- .github/workflows/next-build.yaml
Change-Id:...
enable travis for :next builds
Change-Id: Id9f9c6883c4516f5ab75288ac5aaf9707303bf98
N/A
N/A (or see commit message above for issue number)
N/A
> enable travis for :next builds

- .github/workflows/release.yml
- .github/workflows/try-in-web-ide.yaml
https://github.com/eclipse/che/issues/20664
> chore: Add try in Web IDE action

- README.md
no-op change to test GH PR commit automation
N/A
N/A (or see commit message above for issue number)
N/A
> no-op change to test GH PR commit automation

- build/dockerfiles/brew.Dockerfile
- build/dockerfiles/rhel.Dockerfile
Update brew.Dockerfile to go-toolset:1.19.13-2 to fix CVE
> CRW-4933 Update go-toolset in brew.Dockerfile

- build/dockerfiles/brew.Dockerfile
- build/dockerfiles/rhel.Dockerfile
In my haste for 3.9 I made the changes to the 7.74 branch but not main. oops.
> Check in go changes for CRW-4933 to main

- build/dockerfiles/brew.Dockerfile
- build/dockerfiles/rhel.Dockerfile
Cherry pick of changes from main. Forgot that we'd released 7.76 and need this in 3.11 as well.
> Check in go changes for CRW-4933 to 7.76.x

- build/dockerfiles/rhel.Dockerfile
CRW-4977, some rpms are out of date
> Update rpms from ubi8-minimal

- cloud-shell/package.json
- cloud-shell/yarn.lock
```
"cipher-base": "^1.0.6",
"sha.js": "^2.4.12"
```
> fix: Update sha.js and cipher-base dependencies
