- assembly/etc/che-plugin.yaml
Disable discoverability of exec endpoint which is not used at the moment and prevents starting several workspaces in the same k8s namespace.
Video that shows that exec works with this change https://www.youtube.com/watch?v=TFrQzmMHIL0
> Disable discoverability of endpoint

- exec/exec-manager-provider.go
https://github.com/eclipse/che-machine-exec/issues/14
> Don't fail che-machine-exec container in case unsupported infra

- CONTRIBUTING.md
- CONTRIBUTION.md
- devfile.yaml
- dockerfiles/ci/Dockerfile
- dockerfiles/dev/Dockerfile
https://github.com/eclipse/che/issues/14126
Introduce CONTRIBUTING.md  file.
> Introduce CONTRIBUTING.md file.

- CONTRIBUTING.md
- devfile.yaml
- dockerfiles/dev/Dockerfile
https://github.com/eclipse/che/issues/14195
1. Use default editor for development.
2. Use newer go plugin for development.
3. Extends development image with default eclipse go dev container to reuse permission fixes on the minishift.
> Improve dev file

- README.md
docs for newly created Centos CI - https://github.com/eclipse/che/issues/14357
> che #14357: Adding build status icons and info about existing CI job to README

- dockerfiles/ci/Dockerfile
- rhel.Dockerfile
https://github.com/eclipse/che/issues/14887
> Add absent /tmp folder in the exec image to fix task SIGINT termination

- RELEASE.md
PR contains `RELEASE.md` with a detailed set of instructions for  Major/Minor and  Service/Bugfix releases of the 'che-machine-exec' plugin
issue https://github.com/eclipse/che/issues/15506
> che #15506 Adding RELEASE.md file with instructions for Major/Minor and  Service/Bugfix releases

- shell/shell_info_parser.go
- shell/shell_info_parser_test.go
Fix shell detection when shell is empty value:
```
user:x:1000:1000:user,,,:/home/user:
```
Last item after `:` (shell) is empty
> Fix shell detection when shell is empty value.

- main.go
It's a workaround of jwtproxy issue that does not work correctly when a secure Che server has non-empty path.
It's related to https://github.com/eclipse/che/issues/15497
> Add redirects from / to static folder

- cloud-shell/src/index.ts
- cloud-shell/src/terminal.ts
Fix return of carriage during the printing of welcome title.
Thank @AndrienkoAleksandr for helping prepare a quick fix!
Before:
After:
```yaml
metadata:
name: cloud-shell
components:
- type: cheEditor
reference: >-
https://gist.githubusercontent.com/sleshchenko/c1cd908303b12684ac21e616c4cee1e9/raw/7e1dc5d106024af49fb1009af0c18792d2b1e328/meta.yaml
alias: cloudShell
- memoryLimit: 256Mi
type: dockerimage
alias: dev
image: 'eclipse/che-remote-plugin-openshift-connector-0.0.17:7.2.0'
env:
- value: '\[\e[34m\]>\[\e[m\]\[\e[33m\]>\[\e[m\]'
name: PS1
apiVersion: 1.0.0
```
> Fix return of carriage during printing of welcome title

- exec/kubernetes_exec_manager.go
Collect any errors encountered while trying to open an exec into each container; if we cannot create an exec, print all errors encountered to aid debugging.
For successful connection, nothing is printed.
This is useful in case of e.g. a rbac issue; if the serviceaccount being used by machine-exec doesn't have enough permissions, it's clear from the logs.
> Collect errors while trying to exec into containers and print them

- cloud-shell/src/const.ts
- cloud-shell/src/index.ts
- cloud-shell/src/terminal-protocol.ts
https://github.com/eclipse/che/issues/16249
> Display exec error or exit information in the UI cloud shell.

- cloud-shell/src/index.ts
This PR was done during work on integration CloudShell + OpenShift Console.
Unfortunately, we figure out that because of security constraints CloudShell frontend can't be run behind OpenShift Console Proxy, but in general it makes sense to avoid absolute references. In the Che perspective, it allows use CloudShell with SingleHost server exposure strategy.
It can be tested with the following Devfile
<details>
<summary>Devfile to test</summary>
```yaml
apiVersion: 1.0.0
metadata:
name: cloud-shell
components:
- alias: cloud-shell
type: cheEditor
reference: https://gist.githubusercontent.com/sleshchenko/c1ae73f1ab4b9c1ee325bf1d5751cfd8/raw/3b2f3c05a4ee082dcff34f54b203273c364b6bb6/meta.yaml
- type: dockerimage
memoryLimit: 256Mi
alias: dev
image: …
```
> Do not use absolute references to work on single host/behind proxy

- api/rest/handlers.go
This PR makes container name required and expect JSON to be sent.
Previously, if content-type is missing container name was not parsed correctly and error `no container with name "" found` was returned. Now if content-type is missing - JSON payload is parsed correctly.
> Make container name required and expect JSON to be sent

- exec/activity-connection-saver.go
- exec/kubernetes_exec_manager.go
- ws-conn/err_handler.go
- ws-conn/ws-connection-handler.go
Close attach websocket connection on exec exit. Add pong handler. Stop activity tracker on exec exit.
https://github.com/eclipse/che/issues/16601
> Close attach websocket connection on exec exit. Add pong handler.

- exec/kubernetes_exec_manager.go
- kubeconfig/kubeconfig.go
Previously if you wanted to create a kubeconfig in a different namespace it would need pod/exec privileges. This PR fixes that so it uses the namespace you are in to get the k8sAPI and then the namespace passed into /exec/init is used in the creation of the kubeconfig.
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
> Use seperate namespace for getting k8sAPI and kubeconfig creation

- README.md
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
This PR updates the build docker image command in the README to point to the dockerfile in the new location.
Right now you'll get:
```
$ docker build --no-cache -t eclipse/che-machine-exec
"docker build" requires exactly 1 argument.
See 'docker build --help'.
Usage:  docker build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile
```
After this PR it will successfully build
> Fix build docker image command in README

- main.go
Add endpoint /healthz that can be polled to check whether the machine-exec server is up and running.
Helps in checking whether a cloudshell is ready to respond to /exec/init, etc.
Image for testing: `docker.io/amisevsk/che-machine-exec:dev`.
Required for https://github.com/che-incubator/che-workspace-operator/pull/78
> Add /healthz endpoint for monitoring server status.

- api/jsonrpc/handlers.go
- api/model/model_types.go
- api/rest/activity.go
- api/rest/execInit.go
- api/rest/execKubeConfig.go
- api/websocket/attach.go
- api/websocket/connect.go
- auth/auth.go
- auth/token.go
- auth/user.go
- cfg/cfg.go
- client/kubernetes_client_provider.go
- common/rest/error.go
- common/rest/response.go
- main.go
- vendor/k8s.io/client-go/dynamic/client.go
- vendor/k8s.io/client-go/dynamic/client_pool.go
- vendor/k8s.io/client-go/dynamic/dynamic_util.go
- vendor/modules.txt
Add an ability to configure authenticated user-id.
It's needed in case the use bearer token is configured, so we must make sure that nobody will personalize with already created exec.
I made authenticated-user-id param stick to use-bearer-token although I could imagine that che-machine-exec could be run behind a proxy that already has such check.
But we'll be able to change it later.
It fixes https://github.com/eclipse/che/issues/16489
It depends on https://github.com/che-incubator/che-workspace-operator/pull/77
See how it works for workspace created by developer:
^ right-hand side - kube:admin, left-had side developer
> Add an ability to configure authenticated user-id

- activity/manager.go
- api/rest/activity.go
- auth/auth.go
- auth/token.go
- auth/user.go
- cfg/cfg.go
- client/kubernetes_client_provider.go
- common/rest/response.go
- main.go
This PR makes che-machine-exec track activity and stop workspace CR by idle timeout.
It solves https://github.com/eclipse/che/issues/16683
> Make che-machine-exec track activity and stop workspace CR by idle timeout

- cfg/cfg.go
- main.go
Add flag `--use-tls`, which, if enabled, makes machine-exec serve all content over TLS.
Required for https://github.com/che-incubator/che-workspace-operator/pull/71
> Support serving data via TLS

- auth/token.go
Fix reading header `X-Access-Token`, which should have the form `Bearer <token>`
> Fix reading of token from X-Access-Token header

- build/dockerfiles/rhel.Dockerfile
Updates base build image from rhel8/go-toolset:1.13.4-22 to rhel8/go-toolset:1.13.4-27
It's generated automatically with `../codeready-workspaces/product/updateBaseImages.sh -b updateRHELBaseImage -w ./build/dockerfiles -f rhel.Dockerfile`
> Update base build image from rhel8/go-toolset:1.13.4-22 to rhel8/go-toolset:1.13.4-27

- .github/workflows/gh_actions_pr.yaml
- .github/workflows/gh_actions_push.yaml
Refference issue: https://github.com/eclipse/che/issues/17875
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
> Migrate nightly jobs from ci centos to GH actions

- activity/manager.go
This PR updates the activity manager to add the reason why a DevWorkspace was stopped.
Related PR: https://github.com/devfile/devworkspace-operator/pull/190
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
> Add stopped-by annotation for adding the reason why a DevWorkspace was stopped

- .github/workflows/gh_actions_pr.yaml
This PR fixes multiarch PR check in the same way @akurinnoy fixed for dashboard.
Multiarch build is done in independently, only `linux/amd64` is required since it's the most stable and if it fails then probably there is something wrong with changes but not unstable build.
You may check that before PRs were merged without that check since it was really rarely this check is successful.
> Fix multiarch PR check

- .github/workflows/gh_actions_pr.yaml
- .github/workflows/gh_actions_push.yaml
$ docker run --rm -it quay.io/eclipse/che-machine-exec:nightly                                                                                                                                                              Unable to find image 'quay.io/eclipse/che-machine-exec:nightly' locally
Digest: sha256:c25227a7dc501638e2108797ae634fdc86b2ddd9eae3bdd09d2507295ba60ab7
Status: Downloaded newer image for quay.io/eclipse/che-machine-exec:nightly
WARNING: The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
INFO[0000] Default 'info' log level is applied
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
> Fix machine exec build

- activity/manager.go
- filter/kubernetes_filter.go
Removing check for env.Name to adapt to che sidecar removal from devworkspace operator.
Issue Reference: https://github.com/devfile/devworkspace-operator/issues/344
Related to: https://github.com/devfile/devworkspace-operator/pull/347
> removing env.Name check to adapt to che sidecar env var removal

- .github/workflows/codecov.yml
Removes CODECOV_TOKEN from GitHub action.
It isn't needed [1] and it is compromised [2]
[1] https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token
[2] https://about.codecov.io/security-update/
> Remove `CODECOV_TOKEN` from GitHub action

- build/dockerfiles/Dockerfile
Sometimes if Dockerfile don't have in FROM the registry url, using podman is hard to automatize build images. Podman Terminal on building:
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
> Add docker.io to FROM container name

- build/dockerfiles/Dockerfile
- build/dockerfiles/rhel.Dockerfile
Image puller is executing `sleep` command but scratch images don't have this utility
Adds the `self-contained` sleep utility to make it working
related to https://github.com/eclipse/che/issues/19755
Change-Id: Ic91decb30d5f7cc66f01e1cdd18a8b5fe3c7c4fe
Signed-off-by: Florent Benoit <fbenoit@redhat.com>
> feat(sleep): Add sleep utility to make it compliant with image puller

- build/dockerfiles/rhel.Dockerfile
- go.mod
feat: Switch to golang 1.15
https://github.com/eclipse/che/issues/19764
> feat: Switch to golang 1.15

- api/rest/activity.go
- cfg/cfg.go
- main.go
- timeout/inactivity.go
- timeout/run.go
- timeout/shutdown.go
Signed-off-by: David Kwon <dakwon@redhat.com>
Part of https://github.com/eclipse/che/issues/21390
This PR introduces two features:
1. reads the following environment variables set the activity idling timeout and run timeout respectively:
- `SECONDS_OF_DW_INACTIVITY_BEFORE_IDLING`:  the number of seconds after which a workspace is stopped if there is no user activity (in other words, no requests to machine-exec's `/activity/tick` endpoint)
- `SECONDS_OF_DW_RUN_BEFORE_IDLING`: the number of seconds after which a workspace is stopped, regardless of user activity. This feature is synonymous to [CHE_LIMITS_WORKSPACE_RUN_TIMEOUT](https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#_che_limits_workspace_run_timeout) from the …
> feat: read timeouts from env variables, implement run timeout

- timeout/shutdown.go
Signed-off-by: David Kwon <dakwon@redhat.com>
Fixes https://github.com/eclipse/che/issues/21549#issuecomment-1185967059
To test this PR:
1. In the CheCluster CR, set `spec.devEnvironments.secondsOfRunBeforeIdling` to `30`
2. Create a workspace with the following factory url:
```
{CHE-HOST}/#https://github.com/che-samples/golang-example/tree/devfilev2?che-editor=https://gist.githubusercontent.com/dkwon17/ca3129222898f8f65ef5a9cd5a6945fb/raw/758a9dcd578d5d5b96e532a764290b40ff257ffa/checode-v1alpha2
```
3. Wait until the workspace pod terminates due to the run timeout set at step 1.
4. Verify that `spec.template.attributes` of the devworkspace was not cleared.
> fix: update DevWorkspace group version

- cfg/cfg.go
- timeout/inactivity.go
- timeout/run.go
- timeout/shutdown.go
This PR introduces two fixes for the workspace timeouts:
1. Fix the default timeouts that were incorrectly set in: https://github.com/eclipse-che/che-machine-exec/pull/208
2. The `"controller.devfile.io/stopped-by"` annotation was always set to `"inactivity"` when machine-exec stopped a workspace regardless if it was a run timeout or an idle (inactivity) timeout. In this PR, `"controller.devfile.io/stopped-by"` is set to `"run-timeout"` if the workspace has been stopped due to run timeout.
> Small fixes for workspace timeouts

- .github/workflows/codecov.yml
- .github/workflows/dependencies-md-check.yaml
- .github/workflows/gh_actions_pr.yaml
- .github/workflows/gh_actions_unit.yaml
- .github/workflows/license.yaml
- .github/workflows/next-build.yaml
- .github/workflows/release.yml
- .github/workflows/try-in-web-ide.yaml
Signed-off-by: sdawley <sdawley@redhat.com>
Addresses issue: https://github.com/eclipse/che/issues/21763
> Chore: Update GitHub actions to use node 16 and Ubuntu to latest

- .github/workflows/release.yml
- make-release.sh
Disable provenance for buildx builds
See issue https://github.com/eclipse/che/issues/21954
> Set provenance:false for buildx builds

- build/dockerfiles/README.md
- build/dockerfiles/brew.Dockerfile
The README is mostly so people know not to try to use brew.Dockerfile.
> Chore: CRW-4043 adding brew.Dockerfile and readme explaining Dockerfiles

- build/dockerfiles/Dockerfile
- go.mod
- vendor/modules.txt
[CRW-4552](https://issues.redhat.com/browse/CRW-4552) - update github.com/gin-gonic/gin to 1.9.1 (also resolves [CRW-4502](https://issues.redhat.com/browse/CRW-4502))
[CRW-3890](https://issues.redhat.com/browse/CRW-3890) - was resolved by updating brew.Dockerfile to go-toolset:1.19.13, but this made downstream no longer consistent so I updated Dockerfile to use golang:1.19.13-alpine and updated go to 1.19 in go.mod.
> Changes for CRW-4552, CRW-4502 and CRW-3890

- build/dockerfiles/rhel.Dockerfile
Cherry-pick 4e84e7947565e5758e3294ef846ffcfa6210dff4 from 7.74.x for [CRW-4977](https://issues.redhat.com//browse/CRW-4977)
* Update rpms from ubi8-minimal
[CRW-4977](https://issues.redhat.com//browse/CRW-4977), some rpms are out of date
* Remove -q
> Update rpms from ubi8-minimal (#270)

- make-release.sh
Use `gh` tool instead of `hub` tool, that was removed from the workflow runner
related to  https://github.com/eclipse/che/issues/22646
> fix: che-22646 use gh instead of hub

- exec/kubernetes_exec_manager.go
When creating a new terminal, queue the initial number of rows/columns in the resize channel after starting to ensure the terminal uses the correct initial size (this requires making the channel buffered).
This _should_ fix https://github.com/eclipse/che/issues/22584, except when testing it in the Code editor, the `initialDimensions` sent to machine-exec are wrong -- resizing the terminal pane by even a few pixels shows the new computed size is 7-9 characters wider.
These changes are built into `quay.io/amisevsk/che-code:terminal-size` (with some additional logging to allow debugging terminal size issues). 
To test these changes:
1. Start a Che workspace
2. In the Code terminal, run the following command to change the che-code image: 
```
oc get dwt che-code-$DEVWORKSPACE_NAME -o yaml | …
```
> Use initial terminal size when creating a terminal
